### ISSUE TITLE
torch.cuda.is_available() is False.

### ISSUE THREAD

**Issue by longmalongma** [iMoonLab/PVRNet#1]
Hello,Think your for your work,when I tried to run your code ,I met this problem.can you tell me how to solve this problem?
raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location='cpu' to map your storages to the CPU.

**Comment by Hxyou** [comment]
It seems you need a GPU and correctly configure it with CUDA, CUDNN.

**Comment by longmalongma** [comment]
Think your for your reply,I successfully make it ,I want to know your version about cuda,cudnn,pytorch,do you have code about this parper on the tensorflow?

**Comment by Hxyou** [comment]
The version of cuda and pytorch are listed in readme of our project. And the version of cudnn is 7.1.2. I am sorry to not have tensorflow code.

**Comment by longmalongma** [comment]
I want to know how I test my deep learning environment pytorch-gpu is useful？because I doubt my environment meet problem




------------------ Original ------------------
