### ISSUE TITLE
 the dimensional transformation of the input point cloud

### ISSUE THREAD

**Issue by 16619884724** [iMoonLab/PVRNet#8]
Hello, your work is excellent, I have a question to be solved, the input point cloud dimension should be BXNXdim, why not see the dimension transformation in your code, but in the defined functions like [gather_neighbor] and [get_neighbor_feature], There is batch_size = x.size()[0] ;num_dim = x.size()[1] ; num_point = x.size()[2], the input is BXdimXN?why? I am very confused.I am looking forward to your answer.

**Comment by Hxyou** [comment]
Our input point cloud data dimension is indeed Bx3xN (also in .npy data). 3 means exactly XYZ coordinates.
